Repository StoyanTinchev/musicial-tesla-coil, pull requests merged in 2021-04, with the labels that each got.

#7 Add feature for get song file images
  .gitignore
  Music app/.gitignore
  Music app/app/build.gradle
  Music app/app/src/main/AndroidManifest.xml
  Music app/app/src/main/java/com/example/musicapp/AlbumFragment.java
  Music app/app/src/main/java/com/example/musicapp/MainActivity.java
  Music app/app/src/main/java/com/example/musicapp/MusicFile.java
  Music app/app/src/main/java/com/example/musicapp/SongsFragment.java
  Music app/app/src/main/res/layout/fragment_songs.xml
  Music app/app/src/main/res/values-night/themes.xml
  Music app/build.gradle
  Music app/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#10 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, question

#11 Create pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: enhancement

#13 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement, question

#16 Added Interrupter Software
  Interrupter Software/.gitignore
  Interrupter Software/Makefile
  Interrupter Software/drivers/eepromdvrsrc.c
  Interrupter Software/drivers/includes/eepromdvrinc.h
  Interrupter Software/drivers/includes/uartdvrinc.h
  Interrupter Software/drivers/uartdvrsrc.c
  Interrupter Software/functionalities/command.c
  Interrupter Software/functionalities/includes/command.h
  Interrupter Software/functionalities/includes/music.h
  Interrupter Software/functionalities/includes/upload.h
  Interrupter Software/functionalities/music.c
  Interrupter Software/functionalities/upload.c
  Interrupter Software/main.c
Labels: enhancement
